### ISSUE TITLE
Format issue about the anno.csv files in findVariants.txt

### ISSUE THREAD

**Issue by Tianqi-Ma** [ThomasJamesMitchell/deSCeRNAMut#1]
Hi, Thomas

Thank you very much for sharing scripts and I'm very interested in reproducing this workflow on my own data.

I'm currently confused with the content in anno.csv files which showed up at the beginning of findVariants.txt.

Are they coming from the cell type annotation results whcih provided by the data owner? And what do they look like? 

It's a bit abstract to build such anno.csv file without a templet.

It would be much helpful if sample data can be provided to reproduce the results of existed scripts.

Have a nice day!

**Comment by ThomasJamesMitchell** [comment]
Thank you for your interest. The anno file links cell barcode with cell type. In this instance, it is only used to create a file of barcodes of cells that have passed QC, that we want to run the initial mutation calling pile up in. My files look like this (this is for fibroblasts). The script only uses the rowname to generate a file for each sequencing lane (the 5739STDY part) and which cells have been sequenced:
,patient,summaryDescription,seurat_clusters,scienceIDType,annotation
5739STDY7958791_ACCAGTACATGCCTAA-1,PD43948,Metastasis,0,Fibroblast,CYGB+_Myofibro
5739STDY7958791_AGCCTAAAGGGATGGG-1,PD43948,Metastasis,3,Fibroblast,MHC-II_Myofibro
5739STDY7958791_CAAGATCTCGTACCGG-1,PD43948,Metastasis,1,Fibroblast,CCN1+_Myofibro

**Comment by Tianqi-Ma** [comment]
Got it. Much appreciated.
