### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by HMU-ZSN** [ThomasJamesMitchell/deSCeRNAMut#2]
Thanks to the author for the code. But I have some confusions. Following this flow, do we get mutations based on cell type rather than per cell? Because I found that when concatenate vcfs, the mutations of every 1,000 cells were finally merged together, and the barcode of the cell could not be distinguished. I don't know if I made a mistake here.
And what is deposited in the file 'studyInfo.txt' ? Since there is no example data, I'm not quite sure what information is being extracted by some of the code involved in this file. Could you please tell me?
Sorry to bother you. Thank you again.

**Comment by ThomasJamesMitchell** [comment]
Many thanks for your questions. This code has now been refined much further and put together in a more usable method in:

https://github.com/cortes-ciriano-lab/SComatic/

I would recommend that you use this.

In answer to your questions, the concatenate vcf step is only finding possible mutation loci. These loci are then interrogated in each cell to get barcode and mutation status information. The studyinfo file links sequencing lane with patient.

I hope this helps.

**Comment by HMU-ZSN** [comment]
Many thanks for your kind reply and the new method provided. I will study the optimization methods carefully. Thank you again.


 ***@***.***
 ***@***.***
  



---- Replied Message ----
From  Thomas ***@***.***> Date  04/17/2023 21:48 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [ThomasJamesMitchell/deSCeRNAMut] Asking for help (Issue #2)  

Many thanks for your questions. This code has now been refined much further and put together in a more usable method in:
https://github.com/cortes-ciriano-lab/SComatic/
I would recommend that you use this.
In answer to your questions, the concatenate vcf step is only finding possible mutation loci. These loci are then interrogated in each cell to get barcode and mutation status information. The studyinfo file links sequencing lane with patient.
I hope this helps.

**Comment by HMU-ZSN** [comment]
I'm sorry to bother you again.
 I used the SComatic method recommended by you to process the data. But I had a new problem. With deSCeRNAMut, mutations can be refined to a single cell level (because bam files can be split by barcode), and as described in the SComatic article, it seemed possible to do this as well. However, in the website you provided, I did not find the relevant code to recognize the mutation at  single cell level, and the final result is only stuck at the cell type level. So I want to know if SComatic can do this, and if so, how should I do it?
Thank you very much. Looking forward to your reply.


---- Replied Message ----
From  Thomas ***@***.***> Date  04/17/2023 21:48 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [ThomasJamesMitchell/deSCeRNAMut] Asking for help (Issue #2)  

Many thanks for your questions. This code has now been refined much further and put together in a more usable method in:
https://github.com/cortes-ciriano-lab/SComatic/
I would recommend that you use this.
In answer to your questions, the concatenate vcf step is only finding possible mutation loci. These loci are then interrogated in each cell to get barcode and mutation status information. The studyinfo file links sequencing lane with patient.
I hope this helps.
