### ISSUE TITLE
Asking for Help

### ISSUE THREAD

**Issue by yuansh3354** [ThomasJamesMitchell/deSCeRNAMut#3]
Thank you to the author for generously sharing the code. I would like to request the part of the data used in the code, specifically for when running the "scripts/collateCounts.txt" section of the code. I need two files, namely "mutCalling/data/DARNEDHg19to38.tsv" and "mutCalling/data/TABLE1_hg38.txt". Could you please advise me on how to obtain these files? Is it possible to request for the raw data that you used?

**Comment by ThomasJamesMitchell** [comment]
Many thanks for your questions. This code has now been refined much further and put together in a more usable method in:

https://github.com/cortes-ciriano-lab/SComatic/

I would recommend that you use this as this version will be updated and referenced in the future.
